### ISSUE TITLE
install client index fail 

### ISSUE THREAD

**Issue by yanganto** [atlasr-org/atlasr#5]
fail to run `just install-client-index`

sed: can't read s@{MAP-PLACEHOLDER.svg}@%3csvg xmlns='http://www.w3.org/2000/svg' width='1024' height='540' version='1'%3e%3cfilter id='blur'%3e%3cfeGaussianBlur stdDeviation='12' /%3e%3c/filter%3e%3cg filter='url(%23blur)'%3e%3cpath fill='%23e7e4d9' d='M0 0h1024v540H0z'/%3e%3cpath fill='%23a9cff7' d='M162 554l300-340-100 220z'/%3e%3cpath fill='%23b4d0ed' d='M690 126l240-48 128 72z'/%3e%3cpath fill='%23aacded' d='M454 202l308-96H590z'/%3e%3cpath fill='%23cedfc0' d='M702 450L466 126l-128 64z'/%3e%3cpath fill='%23f3e8e0' d='M602-62L-18 602 166-58z'/%3e%3cpath fill='%23dfe1b4' d='M878-62l204 160-208-12z'/%3e%3cpath fill='%23f1e8df' d='M1086 506l-908 96 224-240z'/%3e%3cpath fill='%23b8d3fc' d='M414 298l60-112 92-48z'/%3e%3cpath fill='%23d7e2be' d='M894 302l-80-12 64-228z'/%3e%3cpath fill='%23d3ddb2' d='M6 310l92-32-76-80z'/%3e%3cpath fill='%23f1e9e2' d='M874 130l116 4-4 404z'/%3e%3cpath fill='%23dde1a4' d='M-62 6L66-58-62 286z'/%3e%3cpath fill='%23f2e2b8' d='M458 274l216-140-112 24z'/%3e%3cpath fill='%23a6cef7' d='M262 514l-48-20-108 108z'/%3e%3cpath fill='%23f1e8df' d='M526 178l288 376 16-420z'/%3e%3cpath fill='%23f5e9d9' d='M918 102L690-62 438 98z'/%3e%3cpath fill='%23f1e2b0' d='M782 90L678 74l-100 40z'/%3e%3cpath fill='%23eeddaf' d='M394 230l-40 104 128-164z'/%3e%3cpath fill='%23dbdec2' d='M318 134l132-24 24 120z'/%3e%3cpath fill='%23ebddc0' d='M442 446l-88-140 104 96z'/%3e%3cpath fill='%23f8efec' d='M530 326l-100-20 24 132z'/%3e%3cpath fill='%23e2dab7' d='M830 378v200l32-112z'/%3e%3cpath fill='%23afd0ef' d='M1018 118l-120-12 180 72z'/%3e%3cpath fill='%23ffecda' d='M978 86l80-148 28 236z'/%3e%3cpath fill='%23eee0cb' d='M78 42l48 176 84-108z'/%3e%3cpath fill='%23f6ede5' d='M22 66L90-62 70 266z'/%3e%3cpath fill='%23b9d5f3' d='M514 146l116-32-196 128z'/%3e%3cpath fill='%23eee7e1' d='M86 586L-62 314l444-40z'/%3e%3cpath fill='%23eae0ca' d='M302 566l-132 36 224-212z'/%3e%3cpath fill='%23d4e7c6' d='M690 406l-64 36-112-228z'/%3e%3cpath fill='%23b5d3f1' d='M734 138l12-40 144 16z'/%3e%3cpath fill='%23d4dab5' d='M994 122l-28-96-132-88z'/%3e%3cpath fill='%23e2d7a9' d='M6 178v-60l36-4z'/%3e%3cpath fill='%23eedaa8' d='M298 394l80-92-52 32z'/%3e%3cpath fill='%23f0e9e3' d='M410 246l-88 104-36-172z'/%3e%3cpath fill='%23f6e7c8' d='M1034 174l-68-44-116 8z'/%3e%3cpath fill='%23ead9bd' d='M466 474l156 128 32-48z'/%3e%3cpath fill='%23ede8e2' d='M846 594l228-548-32 520z'/%3e%3cpath fill='%23efd6a5' d='M638 138l12-60 8 76z'/%3e%3cpath fill='%23f5e2c3' d='M302 394l-116 64-72 136z'/%3e%3cpath fill='%23ede7e3' d='M422-62L926 50 654 90z'/%3e%3cpath fill='%23b5d2f4' d='M402 354l44-128-52 68z'/%3e%3cpath fill='%23f6e9d8' d='M454 98l24 64 156-72z'/%3e%3cpath fill='%23f4eeea' d='M774 418L578 602l76-144z'/%3e%3cpath fill='%23feebde' d='M494 210l-36 44 92-64z'/%3e%3cpath fill='%23ded8ba' d='M798 362l4-132 20 56z'/%3e%3cpath fill='%23b89e95' d='M170 138l20-8h-36z'/%3e%3cpath fill='%23e9e1d0' d='M302 378l28-116-116-92z'/%3e%3cpath fill='%23e5d7bf' d='M90 266l40 28 80-16z'/%3e%3cpath fill='%23e6ddba' d='M626 78L490 90l64-32z'/%3e%3cpath fill='%23dedeae' d='M618 142l-24 40-76 24z'/%3e%3cpath fill='%23ffdb8e' d='M498 242l-20-4-20-24z'/%3e%3cpath fill='%23d3e9c2' d='M982 438l20-48v108z'/%3e%3cpath fill='%23e8dfcf' d='M110 514l112-136L22 510z'/%3e%3cpath fill='%23d2c8bf' d='M1018 310l-56-4 44-20z'/%3e%3cpath fill='%23dcd1b0' d='M430 290l36-16-56 72z'/%3e%3cpath fill='%23eeebe6' d='M802 302l20 88 144-100z'/%3e%3cpath fill='%23dee2c7' d='M890 138l12 212-96-216z'/%3e%3cpath fill='%23f2dbaf' d='M126 102l-36-4-52 40z'/%3e%3cpath fill='%23cddab9' d='M802 30l12-92 124 20z'/%3e%3c/g%3e%3c/svg%3e@: No such file or directory
error: Recipe `install-client-index` failed on line 118 with exit code 2

**Comment by Hywan** [comment]
Is it what you're trying to fix in #11?

What's your platform?

**Comment by yanganto** [comment]
Yes, I try to fix it in #11.

I am using Arch Linux
4.19.4-arch1-1-ARCH

and here is my sed
sed (GNU sed) 4.5
