### ISSUE TITLE
style.json is missing

### ISSUE THREAD

**Issue by yanganto** [atlasr-org/atlasr#7]
The file`style.json` is absent in `static/map-style` nor in `source/map-style`.

**Comment by darrenburns** [comment]
`static/map-style/style.json` is a symlink to `source/map-style/style.json`.

`source/map-style` is a git submodule (defined in the file `.gitmodules`), so when you cloned this project, the directory was there, but it doesn't have any content (this is standard when working with git submodules).

To populate the submodules with files (and fix your problem): 

Run `git submodule init`, followed by `git submodule update`

**Comment by yanganto** [comment]
Thank you.
